displayName=Minimalist
author=Jake
description=Hide non-interactable scenery objects, NPCs, and HUD elements at supported content, starting with Guardians of the Rift
tags=hide,hider,scenery,declutter,minimal,gotr,guardians,rift,entity
plugins=com.minimalist.MinimalistPlugin
build=standard
